name: CI/CD Tienda Backend

on:
  push:
    branches: [ deploy ]
  workflow_dispatch:
    paths:
      - 'backend/**'
      - '.github/workflows/cicd-tienda-backend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Ventas Image
        working-directory: ./backend/back-Ventas_SpringBoot/Springboot-API-REST
        run: |
          docker build -t ${{ secrets.ECR_REPO_URL_BACKEND }}:ventas-latest -t ${{ secrets.ECR_REPO_URL_BACKEND }}:ventas-${{ github.sha }} .
          docker push ${{ secrets.ECR_REPO_URL_BACKEND }}:ventas-latest
          docker push ${{ secrets.ECR_REPO_URL_BACKEND }}:ventas-${{ github.sha }}

      - name: Build, Tag, and Push Despachos Image
        working-directory: ./backend/Springboot-API-REST-DESPACHO
        run: |
          docker build -t ${{ secrets.ECR_REPO_URL_BACKEND }}:despachos-latest -t ${{ secrets.ECR_REPO_URL_BACKEND }}:despachos-${{ github.sha }} .
          docker push ${{ secrets.ECR_REPO_URL_BACKEND }}:despachos-latest
          docker push ${{ secrets.ECR_REPO_URL_BACKEND }}:despachos-${{ github.sha }}

      - name: Download Task Definition (Ventas)
        run: |
          aws ecs describe-task-definition --task-definition tienda-ventas-backend --query taskDefinition > task-def-ventas.json
      
      - name: Download Task Definition (Despachos)
        run: |
          aws ecs describe-task-definition --task-definition tienda-despachos-backend --query taskDefinition > task-def-despachos.json

      - name: Fill in the new image ID in the Amazon ECS task definition (Ventas)
        id: task-def-ventas
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-def-ventas.json
          container-name: ventas-backend
          image: ${{ secrets.ECR_REPO_URL_BACKEND }}:ventas-${{ github.sha }}

      - name: Deploy Amazon ECS task definition (Ventas)
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def-ventas.outputs.task-definition }}
          service: ventas-service
          cluster: tienda-cluster
          wait-for-service-stability: true

      - name: Fill in the new image ID in the Amazon ECS task definition (Despachos)
        id: task-def-despachos
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-def-despachos.json
          container-name: despachos-backend
          image: ${{ secrets.ECR_REPO_URL_BACKEND }}:despachos-${{ github.sha }}

      - name: Deploy Amazon ECS task definition (Despachos)
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def-despachos.outputs.task-definition }}
          service: despachos-service
          cluster: tienda-cluster
          wait-for-service-stability: true
