name: CI/CD Tienda Frontend

on:
  push:
    branches: [ deploy ]
    paths:
      - 'frontend/**'
      - '.github/workflows/cicd-tienda-frontend.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Frontend Image
        working-directory: ./frontend
        run: |
          docker build -t ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest -t ${{ secrets.ECR_REPO_URL_FRONTEND }}:${{ github.sha }} .
          docker push ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest
          docker push ${{ secrets.ECR_REPO_URL_FRONTEND }}:${{ github.sha }}

      - name: Download Task Definition
        run: |
          aws ecs describe-task-definition --task-definition tienda-frontend --query taskDefinition > task-def.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-def.json
          container-name: frontend
          image: ${{ secrets.ECR_REPO_URL_FRONTEND }}:${{ github.sha }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: frontend-service
          cluster: tienda-cluster
          wait-for-service-stability: true
